language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' 
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change 
    on_failure: always 
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "stock-portfolio";' -U postgres 
script:
  - npm test             # test the code
  - npm run build-client # make the bundle


